# Generated by Django 3.2 on 2021-04-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210418_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.shop', to_field='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_category',
            field=models.ManyToManyField(db_column='title', to='polls.Category'),
        ),
        migrations.DeleteModel(
            name='ProductGeneric',
        ),
    ]
